enabled_locales: ["en"]
word:
  per_page: 20
  page_index: 1
  condition: [["Learned", 1], ["Unlearned", 0]]
  number_of_words: 5
courses:
  popular_course: 3
user:
  size: 200x200
relationship:
  cannot_follow_yourself: "can't follow yourself"
lessons:
  correct_answer: "correct-answer"
  incorrect_answer: "incorrect-answer"
  none: ""
  check_square: "check-square"
  square: "square"
